#!/bin/bash
if [ -f /tmp/home ]; then
	exit
else
	sshfs $USER@reddwarf:/srv/docs /mnt/docs
	rm $HOME/{Shared,Music,Video}
	ln -s /mnt/docs/shared $HOME/Shared
	ln -s /mnt/docs/shared/Music $HOME/Music
	ln -s /mnt/docs/shared/Video $HOME/Video
	touch /tmp/home
fi
